[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.7.0"
[[plugins]]
package = "netlify-plugin-a11y"
  [plugins.inputs]
    checkPaths = ['/'] # you can give an array of directories or paths to html files, that you want to run a11y checks on
